spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: community

  profiles:
    active: local

  datasource:
#    url: jdbc:mariadb://localhost:3306/community
#    username: root
#    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://community-db.cxow0weai87b.ap-northeast-2.rds.amazonaws.com/community
    username: admin
    password: {RDS_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

jwt:
  secret: secrtetsecrtetsecrtetsecrtetsecrtetsecrtetsecrtetsecrtetsecrtet
  issuer: connector

except-uri: /api/public/**,/api/health,/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html

server:
  port: 8080